name: Shared Python CI

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt || true

      - run: python -m py_compile $(git ls-files '*.py') || true
